/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package agenda;

import java.awt.Color;
import java.awt.Dimension;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author ioneanua@gmail.com
 */
//splash screen-ul de la incarcarea aplicatiei. Va contine o poza cu infoacademy si un JProgresBar care ne va afisa in cat timp se va incarca aplicatia (timpul ales de mine este de 5 secunde pt a face toate lucrurile acestea vizibile)
public class SpashScreen extends javax.swing.JFrame {
    TimerTask taskSecunde=new TimerTask(){
            @Override
            public void run(){ 
                for(int i=0;i<=5;i++){
           
                    try {
                    jProgressBar2.setValue(i);
                    jProgressBar2.setString(Integer.toString(5-i));
                    if(i==5){
                       new GUI().setVisible(true);
                       dispose();
                    }    
                    Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        return;
                    }
                }
            }
        };
    Timer timerSecunde=new Timer();
    public SpashScreen() {
        initComponents();
        jProgressBar2.setStringPainted(true);
        //afisat frameul pe mijlocul ecranului
        Dimension screenResolution = this.getToolkit().getScreenSize();
        this.setLocation((screenResolution.width - this.getWidth()) / 2, (screenResolution.height - this.getHeight()) / 2);
        //
        jPozaSpashScreen.setIcon(new ImageIcon(getClass().getResource("reclama8.jpg")));
        timerSecunde.schedule(taskSecunde,0);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPozaSpashScreen = new javax.swing.JLabel();
        jStart = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jAutor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridLayout(4, 1));

        jPozaSpashScreen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jPozaSpashScreen);

        jStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jStart.setText("Aplicatia se va incarca in:");
        getContentPane().add(jStart);

        jProgressBar2.setForeground(new java.awt.Color(0, 0, 0));
        jProgressBar2.setMaximum(5);
        getContentPane().add(jProgressBar2);

        jAutor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAutor.setText("Autor: Andrei Ioneanu");
        getContentPane().add(jAutor);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new SpashScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAutor;
    private javax.swing.JLabel jPozaSpashScreen;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JLabel jStart;
    // End of variables declaration//GEN-END:variables
}
